### ISSUE TITLE
website suggestions

### ISSUE THREAD

**Issue by ebeshero** [ajnewton1/PersonalWebsite#3]
Hi @ajnewton1!  I just visited your new personal website and I admire the design! For content, you might want to feature some of the more unusual/interesting things you've done and been part of, like projects you've been working on:
* how about a shout out to the newsAnalysis project somewhere? You redesigned the project site to optimize its layout--(and you did a great job there)--so maybe you could feature that somehow
* And the mobile app design challenge? What other stuff have you been building/learning?
* What kind of IT / design work do you want to be working on / or do you want to be exploring? 

Some of that might appear in the video you have running!
One thing I notice is that I want to type in your message box...;-) In case you want to collect info from site visitors, we can talk about implementing some PHP on your newtFire site.

I'm glad you're working on the site! Every time I visit, the page has changed, which is fun to see. 👍

**Comment by ajnewton1** [comment]
Thanks @ebeshero ! I have been trying to figure out how to center my links on the bottom of the message box and have them stay centered no matter what size the screen is and I am having a little trouble with that. 

And yes, I need to make a shoutout to all the projects that I have done, but I wanted to make those links/shoutouts into application like pictures just like the Resume one looks like. 

PHP sounds very interesting and I would love to get to know more about it. I am able to meet anytime next week with you and Jon.
